name: "weekly sanity test"
on:
  schedule:
    - cron:  '30 20 * * 1'

jobs:
  sanity:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [8, 11, 17]
        impl: [temurin]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.impl }}
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
